DROP TABLE IF EXISTS downloads;
DROP TABLE IF EXISTS visitors;
DROP TABLE IF EXISTS config;

CREATE TABLE IF NOT EXISTS downloads (
  release_tag TEXT PRIMARY KEY,
  count INTEGER DEFAULT 0
);

CREATE TABLE IF NOT EXISTS visitors (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  ip TEXT,
  user_agent TEXT,
  timestamp DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS config (
  key TEXT PRIMARY KEY,
  value TEXT,
  updated_at INTEGER
);
